
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * The MainGUI class provides a GUI using JFrame, Swing, and AWT class methods
 * for the implementation of the simulation of simplifying Boolean functions using
 * the Quine-McCluskey Tabular Method.  
 *
 * @author  Marxel S. Abogado
 * @author  Carla Joy G. Haboc
 * @version 1.0
 * @since   2023-11-21
*/
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("/appicon.png")).getImage();
        this.setIconImage(img);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSolution = new javax.swing.JLabel();
        lblMinterms = new javax.swing.JLabel();
        lblVariables = new javax.swing.JLabel();
        txtVariables = new javax.swing.JTextField();
        txtMinterms = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSolution = new javax.swing.JTextArea();
        cbVariables = new javax.swing.JCheckBox();
        lblVarSubs = new javax.swing.JLabel();
        lblMinSubs = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnSolve = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblAbout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quine-McCluskey Method Simulation");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(470, 470));
        setPreferredSize(new java.awt.Dimension(470, 470));
        setResizable(false);
        setSize(new java.awt.Dimension(470, 470));
        getContentPane().setLayout(null);

        lblSolution.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        lblSolution.setText("Results:");
        lblSolution.setName("lblSolution"); // NOI18N
        getContentPane().add(lblSolution);
        lblSolution.setBounds(40, 300, 100, 19);

        lblMinterms.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        lblMinterms.setText("Minterms:");
        lblMinterms.setName("lblMinterms"); // NOI18N
        getContentPane().add(lblMinterms);
        lblMinterms.setBounds(40, 100, 90, 19);

        lblVariables.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        lblVariables.setText("Variables:");
        lblVariables.setName("lblVariables"); // NOI18N
        getContentPane().add(lblVariables);
        lblVariables.setBounds(40, 160, 100, 19);

        txtVariables.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        txtVariables.setText("A, B, C, D, E, F, G, H, I, J");
        txtVariables.setEnabled(false);
        txtVariables.setName("txtVariables"); // NOI18N
        getContentPane().add(txtVariables);
        txtVariables.setBounds(140, 150, 280, 30);

        txtMinterms.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        txtMinterms.setName("txtMinterms"); // NOI18N
        getContentPane().add(txtMinterms);
        txtMinterms.setBounds(140, 92, 280, 30);

        txaSolution.setEditable(false);
        txaSolution.setColumns(20);
        txaSolution.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        txaSolution.setLineWrap(true);
        txaSolution.setRows(5);
        txaSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txaSolution.setName("txaSolution"); // NOI18N
        jScrollPane1.setViewportView(txaSolution);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 260, 280, 80);

        cbVariables.setFont(new java.awt.Font("Gotham", 2, 12)); // NOI18N
        cbVariables.setText("custom variables?");
        cbVariables.setName("cbCustom"); // NOI18N
        cbVariables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVariablesActionPerformed(evt);
            }
        });
        getContentPane().add(cbVariables);
        cbVariables.setBounds(140, 190, 280, 19);

        lblVarSubs.setFont(new java.awt.Font("Gotham", 2, 10)); // NOI18N
        lblVarSubs.setForeground(new java.awt.Color(102, 102, 102));
        lblVarSubs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVarSubs.setText("default variables used*");
        lblVarSubs.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblVarSubs.setName("lblMinSubs"); // NOI18N
        lblVarSubs.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblVarSubs);
        lblVarSubs.setBounds(140, 217, 280, 20);

        lblMinSubs.setFont(new java.awt.Font("Gotham", 2, 10)); // NOI18N
        lblMinSubs.setForeground(new java.awt.Color(102, 102, 102));
        lblMinSubs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSubs.setText("space or comma separated*");
        lblMinSubs.setName("lblMinSubs"); // NOI18N
        getContentPane().add(lblMinSubs);
        lblMinSubs.setBounds(140, 127, 280, 16);

        lblTitle.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUINE-MCCLUSKEY METHOD SIMULATION");
        lblTitle.setName("lblTitle"); // NOI18N
        getContentPane().add(lblTitle);
        lblTitle.setBounds(70, 50, 330, 15);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 240, 390, 10);

        btnSolve.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSolve.setText("Solve");
        btnSolve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolve.setName("btnSolve"); // NOI18N
        btnSolve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolveMouseClicked(evt);
            }
        });
        getContentPane().add(btnSolve);
        btnSolve.setBounds(90, 360, 130, 30);

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setMaximumSize(new java.awt.Dimension(67, 29));
        btnClear.setMinimumSize(new java.awt.Dimension(67, 29));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(67, 29));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(240, 360, 130, 30);

        jLabel1.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CMSC 130 MP 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 410, 100, 16);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(200, 410, 10, 20);

        lblAbout.setFont(new java.awt.Font("Gotham", 2, 12)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(51, 0, 102));
        lblAbout.setText("About");
        lblAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAbout.setName("lblAbout"); // NOI18N
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
        });
        getContentPane().add(lblAbout);
        lblAbout.setBounds(150, 410, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method implements the event when the "Solve" button is clicked.
     * The text entered by the user on the Minterms text field and optionally
     * on the Variables text field is read. The solve() method from the QuineMcCluskey class
     * solves the entered minterms, and printResults() would print the solutions on the Results
     * text area with respect to variables.
     * 
     */
    private void btnSolveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolveMouseClicked

      
        String minterms = txtMinterms.getText();
        boolean mintermsValid = false;
        lblMinSubs.setForeground(new Color(102,102,102));
        lblMinSubs.setText("space or comma delimited*");
        
        lblVarSubs.setForeground(new Color(102,102,102));
        if (cbVariables.isSelected()){
            lblVarSubs.setText("enter 10 variables, space and comma separated*");
        } else {
            lblVarSubs.setText("default variables used*");
        }
        
        if (!isValidMinterms(minterms)){
            lblMinSubs.setForeground(new Color(204,0,51));
            lblMinSubs.setText("input exceeds maximum value 1024*");
        } else {
            mintermsValid = true;
        }
        
        String variables = txtVariables.getText();
        if (!minterms.isBlank()){
            QuineMcCluskey s = new QuineMcCluskey(minterms);
            s.solve();
            if (mintermsValid && minterms.matches("[\\d,\\s]+"))
                txaSolution.setText(s.printResults(convertVariables(variables)));
        }
    }//GEN-LAST:event_btnSolveMouseClicked
    /**
     * This method implements the event when the "Clear" button is clicked.
     * It resets the input and output areas of the program to blank or default for 
     * the convenience of the user to clear them for a new set of solutions.
     */
    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked

        txtMinterms.setText("");
        txtVariables.setText("A, B, C, D, E, F, G, H, I, J");
        cbVariables.setSelected(false);
        txtVariables.setEnabled(false);
        txaSolution.setText("");
        
        lblVarSubs.setForeground(new Color(102,102,102));
        lblVarSubs.setText("default variables used*");
        
        lblMinSubs.setForeground(new Color(102,102,102));
        lblMinSubs.setText("space or comma delimited*");
    }//GEN-LAST:event_btnClearMouseClicked
    /**
     * This method implements the event when the "Custom Variables" checkbox is checked or unchecked.
     * Checking the box would enable the Variables text field and let the user input custom variables
     * for solving. Unchecking the box would disable the text field again and resets the text to default variables.
     */
    private void cbVariablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVariablesActionPerformed
       
        if (cbVariables.isSelected()){
            lblVarSubs.setText("enter 10 variables, space and comma separated*");
            txtVariables.setEnabled(true);
            txtVariables.setText("");  
        }
        else{
            lblVarSubs.setText("default variables used*");
            txtVariables.setEnabled(false);
            txtVariables.setText("A, B, C, D, E, F, G, H, I, J");
        }
    }//GEN-LAST:event_cbVariablesActionPerformed
    /**
     * This method implements the event when the About label is clicked and
     * would present message dialog box about the details of the program.
     */
    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        JOptionPane.showMessageDialog(null, "CMSC 130 Machine Problem No. 1 \n" +
                "Quine-McCluskey Method Simulation \n\nDeveloped by: \nAbogado, Marxel S. \nHaboc, Carla Joy G." +
                " \n\nSubmitted to: \nMa'am Avegail D. Carpio", "About this program", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblAboutMouseClicked

    /**
     * @param args the command line arguments; unused.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    /**
     * @param s String variable that user input of variables that are delimited by space or comma
     * @return returns a String array with a size of 10 that splits the input String into corresponding elements of the array
     *  
     */
    public String[] convertVariables(String s){
        s = s.replace(",", " "); //for comma-delimited inputs
        String[] variables = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"};
        if (s.trim().equals("")) { // if empty
            return variables;
        }
        String[] a = s.trim().split(" +");
        String[] t = new String[a.length]; // array of minterms
        if (t.length < 10)
            lblVarSubs.setText("variables missing, using default for the rest*");
        for (int i = 0; i < t.length; i++) {
            try { // until it reaches outside bounds; sets default variables for the rest if not 10 variables
                if (a[i].length() > 1)
                    variables[i] = "(" + a[i] + ")";
                else
                    variables[i] = a[i];
            } catch (Exception e) {
                lblVarSubs.setForeground(new Color(204,0,51));
                lblVarSubs.setText("input exceeds 10 variables, using only first 10*");
                
            }
        }
        return variables;
    }
    

    /**
     * @param   s   String variable that user input of minterms
     * @return  returns true if the minterms are Integers from 0 - 1023, else false
     */
    public boolean isValidMinterms(String s){
        s = s.replace(",", " ");
        String[] temp = s.trim().split(" +");
        int[] intMinterms = new int[temp.length];
        for (int i = 0; i < temp.length; i++){
            try {intMinterms[i] = Integer.parseInt(temp[i]);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Invalid input. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                txtMinterms.setText("");
            }
        }
        for (int i = 0; i < intMinterms.length; i++){
            if (intMinterms[i] > 1023)
                return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSolve;
    private javax.swing.JCheckBox cbVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblMinSubs;
    private javax.swing.JLabel lblMinterms;
    private javax.swing.JLabel lblSolution;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVarSubs;
    private javax.swing.JLabel lblVariables;
    private javax.swing.JTextArea txaSolution;
    private javax.swing.JTextField txtMinterms;
    private javax.swing.JTextField txtVariables;
    // End of variables declaration//GEN-END:variables
}
